név = input('Mi a vezetékneved?')
név = input('Mi a keresztneved?')
Név = input ('Mi a csillagjegyed?')
Név = input('Mikor születtél?')
Válasz = input('A nevem')
Válasz = input ('A születési évem és a csillagjegyem')
print(válasz)